services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: foodygo
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      TZ: Asia/Saigon
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+07:00']
  spring-boot-builder:
    container_name: spring-boot-builder
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../maven-cache:/root/.m2
      - ./data/spring-boot-data:/temp/build-output
  spring-boot-runner:
    container_name: spring-boot-runner
    build:
      context: .
      dockerfile: docker/runner/Dockerfile
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/foodygo
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
    ports:
      - "8080:8080"
    depends_on:
      spring-boot-builder:
        condition: service_completed_successfully
    volumes:
      - ./data/spring-boot-data:/temp/build-output
    restart: no
    networks:
      - foodygo-network
  redis:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    networks:
      - foodygo-network

networks:
  foodygo-network:
    driver: bridge