services:
  #BUILDER
  builder:
    container_name: foodygo-builder
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    volumes:
      - ../maven-cache:/root/.m2
      - ./data/spring-boot-data:/temp/build-output
    networks:
      - foodygo-network

  #RUNNER
  runner:
    container_name: foodygo-runner
    build:
      context: .
      dockerfile: docker/runner/Dockerfile
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/foodygo
      MYSQL_USER: root
      MYSQL_PASSWORD: fFP4vTcMY@!NUxgt
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "2222:8080"
    depends_on:
      builder:
        condition: service_completed_successfully
    env_file:
      - local.env
    volumes:
      - ./data/spring-boot-data:/temp/build-output
      - ./data/images:/var/www/images
    networks:
      - foodygo-network
    restart: no

  # REDIS
  redis:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - foodygo-network

  # ZOOKEEPER
  zookeeper:
    container_name: foodygo-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - foodygo-network

  # KAFKA
  kafka:
    container_name: foodygo-kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - foodygo-network

volumes:
  redis:
    name: foodygo-redis

networks:
  mysql-network:
    external: true
  foodygo-network:
    name: foodygo-network
    driver: bridge

#  ollama:
#    image: ollama/ollama
#    container_name: ollama
#    restart: unless-stopped
#    volumes:
#      - ollama_data:/root/.ollama
#    ports:
#      - "11434:11434"
#    tty: true
#    stdin_open: true
#  deepseek:
#    image: ollama/ollama
#    container_name: deepseek
#    restart: unless-stopped
#    command: ["serve"]
#    environment:
#      - OLLAMA_MODEL=deepseek
#    depends_on:
#      - ollama
#volumes:
#  ollama_data:
#    driver: local