services:
  mysql:
    container_name: mysql
    # image: mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: foodygo
      TZ: Asia/Saigon
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  spring-boot-builder:
    container_name: spring-boot-builder
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../maven-cache:/root/.m2
      - ./data/spring-boot-data:/temp/build-output
  spring-boot-runner:
    container_name: spring-boot-runner
    build:
      context: .
      dockerfile: docker/runner/Dockerfile
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/foodygo
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
    ports:
      - "8080:8080"
    depends_on:
      spring-boot-builder:
        condition: service_completed_successfully
    volumes:
      - ./data/spring-boot-data:/temp/build-output
    restart: no