name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 171.250.186.250
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/theanh/GIT/SWD301-FoodyGo-BE/
            docker compose down
            git clean -df
            git fetch --all
            git reset --hard origin/main
            docker compose up --build -d