name: CI/CD Pipeline
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: theanh0804.id.vn
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/theanh/GIT/SWD301-FoodyGo-BE/
            docker compose down
            sudo chmod -R 777 .
            git clean -dfx
            git fetch --all
            git reset --hard origin/production

            echo '${{ secrets.FIREBASE_CREDENTIAL }}' > src/main/resources/firebase-SWD391.json
            
            echo '${{secrets.THEANH_FIREBASE_CREDENTIAL}}' > src/main/resources/theanh-firebase.json
            
            echo '${{secrets.DOT_ENV}}' > local.env

            docker compose up --build -d