name: CI/CD Pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/theanh/GIT/SWD301-FoodyGo-BE/
            git pull
            docker compose down
            docker compose up --build -d